# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: "PHP-SERVER"
    build: './build/php/'
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql-srv
  mysql-srv:
    image: mysql:8.3

    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: viaformation2024!
      MYSQL_DATABASE: FilRougeG3
      MYSQL_USER: db_user
      MYSQL_PASSWORD: viaformation2024!
  adminer:
    image: adminer
    restart: always
    ports:
      - "3306:3306"